apollo:
  bootstrap:
    enabled: true
    # will inject 'application' and 'TEST1.apollo' namespaces in bootstrap phase
    namespaces: application,TEST1.apollo,application.yaml
apollo.autoRefreshConfigurationProperties: com.ctrip.framework.apollo.demo.spring.springBootDemo.autorefresh
